### ISSUE TITLE
Something in the URL extraction fails in strange and foreign domains

### ISSUE THREAD

**Issue by Bike** [kxz/omnipresence#1]
e.g., the message «http://gᴏᴏgle.com i see someone is having a fun» results in

&lt;Omnipresence&gt; Error: 'ascii' codec can't decode byte 0xe1 in position 1: ordinal not in range(128).

the first o is of course LATIN LETTER SMALL CAPITAL O in phonetic extensions, but I imagine the same would happen for other characters.

You told me this was a bug in 2.x, but that release didn't work anyway.

**Comment by kxz** [comment]
This is a combination of Unicode-related problems:
- `URLTitleFetcher.privmsg` should decode the incoming message using the bot's configured encoding. (Arguably, this is something that ought to happen for every command message.)
- `extract_urls` should run over and return a Unicode string, not a byte string.
- Little Brother, the underlying fetcher, should take IRIs (basically Unicode URLs) and encode them as appropriate. (The `escaped_fragment` logic should probably be moved inside there as well.)
- The actual failing line is `return u'[{}] Error: {:s}'.format(hostname, message or failure.value)`. I believe the decode error arises from trying to implicitly convert `hostname` from bytes to Unicode. The fact that I'm guessing here about what's Unicode and what isn't means that the typing needs to be more rigorous.

This should definitely get fixed for 3.x, considering I haven't written the `url` plugin implementation for that version. Then I can backport the tests and fix 2.x.

**Comment by kxz** [comment]
This should be fixed with the rewritten 3.0 version committed in 35dc179. I'll backport this to 2.x when I have time.
